/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   eiku_keycode_from_xkeysym.c                        :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: automated-migration <dev@local>             +#+  +:+       +#+ */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/09/24 00:00:00 by automated-migration  #+#    #+# */
/*   Updated: 2025/09/24 00:00:00 by automated-migration ###   ########.fr */
/*                                                                            */
/* ************************************************************************** */

#include "input/keyboard.h"

#ifdef EIKU_PLATFORM_LINUX

#include <X11/keysym.h>

EIKU_INT t_keycode eiku_keycode_from_xkeysym(KeySym keysym) {
  switch (keysym) {
    case XK_a:
    case XK_A:
      return EIKU_KEY_A;
    case XK_b:
    case XK_B:
      return EIKU_KEY_B;
    case XK_c:
    case XK_C:
      return EIKU_KEY_C;
    case XK_d:
    case XK_D:
      return EIKU_KEY_D;
    case XK_e:
    case XK_E:
      return EIKU_KEY_E;
    case XK_f:
    case XK_F:
      return EIKU_KEY_F;
    case XK_g:
    case XK_G:
      return EIKU_KEY_G;
    case XK_h:
    case XK_H:
      return EIKU_KEY_H;
    case XK_i:
    case XK_I:
      return EIKU_KEY_I;
    case XK_j:
    case XK_J:
      return EIKU_KEY_J;
    case XK_k:
    case XK_K:
      return EIKU_KEY_K;
    case XK_l:
    case XK_L:
      return EIKU_KEY_L;
    case XK_m:
    case XK_M:
      return EIKU_KEY_M;
    case XK_n:
    case XK_N:
      return EIKU_KEY_N;
    case XK_o:
    case XK_O:
      return EIKU_KEY_O;
    case XK_p:
    case XK_P:
      return EIKU_KEY_P;
    case XK_q:
    case XK_Q:
      return EIKU_KEY_Q;
    case XK_r:
    case XK_R:
      return EIKU_KEY_R;
    case XK_s:
    case XK_S:
      return EIKU_KEY_S;
    case XK_t:
    case XK_T:
      return EIKU_KEY_T;
    case XK_u:
    case XK_U:
      return EIKU_KEY_U;
    case XK_v:
    case XK_V:
      return EIKU_KEY_V;
    case XK_w:
    case XK_W:
      return EIKU_KEY_W;
    case XK_x:
    case XK_X:
      return EIKU_KEY_X;
    case XK_y:
    case XK_Y:
      return EIKU_KEY_Y;
    case XK_z:
    case XK_Z:
      return EIKU_KEY_Z;
    case XK_1:
      return EIKU_KEY_1;
    case XK_2:
      return EIKU_KEY_2;
    case XK_3:
      return EIKU_KEY_3;
    case XK_4:
      return EIKU_KEY_4;
    case XK_5:
      return EIKU_KEY_5;
    case XK_6:
      return EIKU_KEY_6;
    case XK_7:
      return EIKU_KEY_7;
    case XK_8:
      return EIKU_KEY_8;
    case XK_9:
      return EIKU_KEY_9;
    case XK_0:
      return EIKU_KEY_0;
    case XK_Return:
      return EIKU_KEY_RETURN;
    case XK_Escape:
      return EIKU_KEY_ESCAPE;
    case XK_BackSpace:
      return EIKU_KEY_BACKSPACE;
    case XK_Tab:
      return EIKU_KEY_TAB;
    case XK_space:
      return EIKU_KEY_SPACE;
    case XK_minus:
      return EIKU_KEY_MINUS;
    case XK_equal:
      return EIKU_KEY_EQUALS;
    case XK_bracketleft:
      return EIKU_KEY_LEFTBRACKET;
    case XK_bracketright:
      return EIKU_KEY_RIGHTBRACKET;
    case XK_backslash:
      return EIKU_KEY_BACKSLASH;
    case XK_semicolon:
      return EIKU_KEY_SEMICOLON;
    case XK_apostrophe:
      return EIKU_KEY_APOSTROPHE;
    case XK_grave:
      return EIKU_KEY_GRAVE;
    case XK_comma:
      return EIKU_KEY_COMMA;
    case XK_period:
      return EIKU_KEY_PERIOD;
    case XK_slash:
      return EIKU_KEY_SLASH;
    case XK_Caps_Lock:
      return EIKU_KEY_CAPSLOCK;
    case XK_F1:
      return EIKU_KEY_F1;
    case XK_F2:
      return EIKU_KEY_F2;
    case XK_F3:
      return EIKU_KEY_F3;
    case XK_F4:
      return EIKU_KEY_F4;
    case XK_F5:
      return EIKU_KEY_F5;
    case XK_F6:
      return EIKU_KEY_F6;
    case XK_F7:
      return EIKU_KEY_F7;
    case XK_F8:
      return EIKU_KEY_F8;
    case XK_F9:
      return EIKU_KEY_F9;
    case XK_F10:
      return EIKU_KEY_F10;
    case XK_F11:
      return EIKU_KEY_F11;
    case XK_F12:
      return EIKU_KEY_F12;
    case XK_Print:
      return EIKU_KEY_PRINTSCREEN;
    case XK_Scroll_Lock:
      return EIKU_KEY_SCROLLLOCK;
    case XK_Pause:
      return EIKU_KEY_PAUSE;
    case XK_Insert:
      return EIKU_KEY_INSERT;
    case XK_Home:
      return EIKU_KEY_HOME;
    case XK_Page_Up:
      return EIKU_KEY_PAGEUP;
    case XK_Delete:
      return EIKU_KEY_DELETE;
    case XK_End:
      return EIKU_KEY_END;
    case XK_Page_Down:
      return EIKU_KEY_PAGEDOWN;
    case XK_Right:
      return EIKU_KEY_RIGHT;
    case XK_Left:
      return EIKU_KEY_LEFT;
    case XK_Down:
      return EIKU_KEY_DOWN;
    case XK_Up:
      return EIKU_KEY_UP;
    case XK_Num_Lock:
      return EIKU_KEY_NUMLOCK;
    case XK_KP_Divide:
      return EIKU_KEY_KP_DIVIDE;
    case XK_KP_Multiply:
      return EIKU_KEY_KP_MULTIPLY;
    case XK_KP_Subtract:
      return EIKU_KEY_KP_SUBTRACT;
    case XK_KP_Add:
      return EIKU_KEY_KP_ADD;
    case XK_KP_Enter:
      return EIKU_KEY_KP_ENTER;
    case XK_KP_1:
      return EIKU_KEY_KP_1;
    case XK_KP_2:
      return EIKU_KEY_KP_2;
    case XK_KP_3:
      return EIKU_KEY_KP_3;
    case XK_KP_4:
      return EIKU_KEY_KP_4;
    case XK_KP_5:
      return EIKU_KEY_KP_5;
    case XK_KP_6:
      return EIKU_KEY_KP_6;
    case XK_KP_7:
      return EIKU_KEY_KP_7;
    case XK_KP_8:
      return EIKU_KEY_KP_8;
    case XK_KP_9:
      return EIKU_KEY_KP_9;
    case XK_KP_0:
      return EIKU_KEY_KP_0;
    case XK_KP_Decimal:
      return EIKU_KEY_KP_DECIMAL;
    case XK_Control_L:
      return EIKU_KEY_LCTRL;
    case XK_Shift_L:
      return EIKU_KEY_LSHIFT;
    case XK_Alt_L:
      return EIKU_KEY_LALT;
    case XK_Super_L:
      return EIKU_KEY_LGUI;
    case XK_Control_R:
      return EIKU_KEY_RCTRL;
    case XK_Shift_R:
      return EIKU_KEY_RSHIFT;
    case XK_Alt_R:
      return EIKU_KEY_RALT;
    case XK_Super_R:
      return EIKU_KEY_RGUI;
    default:
      return EIKU_KEY_UNKNOWN;
  }
}

#endif
