name: Feature Request
description: Suggest a new feature or enhancement for Eiku
title: "[Feature] "
labels: [enhancement]
assignees:
  - cliftontoaster-reid

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see added.
      placeholder: Briefly describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        Example: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: |
        Describe the solution you'd like.
        How should this feature work?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Eiku would this feature affect?
      options:
        - Core (engine fundamentals)
        - Renderer (graphics/rendering)
        - Audio (sound system)
        - Input (keyboard/mouse)
        - Math (mathematics library)
        - Resources (file/asset management)
        - Scene (entity/component system)
        - Build System (Makefile)
        - Documentation
        - Examples
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be useful
        - Important for my use case
        - Critical/blocking
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: |
        Describe alternatives you've considered.
        Are there workarounds you're currently using?

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have any ideas about how this could be implemented?
      placeholder: |
        If you have technical ideas about implementation, share them here.
        This is optional but can be helpful.

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Provide examples of how this feature would be used.
      placeholder: |
        Show code examples or usage scenarios.
        This helps clarify the expected API/behavior.
      render: c

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request.
      placeholder: |
        Any additional information that might be helpful.
        Links to similar features in other engines, references, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues/features that might be related to this request
          required: true
        - label: This feature request is specific to Eiku (not a general C/programming question)
          required: true
        - label: I have provided a clear use case for this feature
          required: true
